SELECT ACC_NO, ACC_TYPE, BALANCE
FROM ACCOUNT
WHERE BRANCH_CODE IN ('B001','B002','B003','B005');

SELECT *
FROM CUSTOMER
WHERE CUST_NAME LIKE 'A%'
AND ADDRESS='Delhi';

SELECT CUST_NO, ACC_NO, BALANCE,
       BALANCE*0.05 AS INTEREST,
       BALANCE + BALANCE*0.05 AS FINAL_BALANCE
FROM ACCOUNT;

SELECT *
FROM ACCOUNT
WHERE BALANCE BETWEEN 20000 AND 50000;

SELECT *
FROM CUSTOMER
WHERE CUST_NAME LIKE '_m%';

SELECT ACC_NO
FROM ACCOUNT
WHERE ACC_TYPE='Savings'
ORDER BY BALANCE DESC;

UPDATE ACCOUNT
SET BALANCE = BALANCE * 1.10;

UPDATE ACCOUNT
SET BALANCE = BALANCE * 1.05
WHERE ACC_TYPE='Savings'
AND BALANCE < 25000;

SELECT ACC_NO, BALANCE,
       BALANCE*0.06 AS ANNUAL_INTEREST
FROM ACCOUNT;

UPDATE ACCOUNT
SET ACC_TYPE='Savings'
WHERE ACC_TYPE='Current'
AND BALANCE < 45000;

DELETE FROM CUSTOMER
WHERE CUST_NO IN (
    SELECT CUST_NO
    FROM LOAN
    WHERE AMOUNT < 150000
);

DELETE FROM CUSTOMER
WHERE CUST_NAME LIKE '%h';

SELECT AVG(BALANCE)
FROM ACCOUNT
WHERE ACC_TYPE='Savings';

SELECT TRANS_TYPE, AVG(TRANS_AMOUNT)
FROM TRANSACTION_DETAILS
GROUP BY TRANS_TYPE;

SELECT ACC_NO, CUST_NO, BALANCE
FROM ACCOUNT
WHERE BALANCE = (SELECT MAX(BALANCE) FROM ACCOUNT);

SELECT COUNT(*)
FROM CUSTOMER
WHERE ADDRESS IN ('Delhi','Mumbai');

SELECT SUM(AMOUNT)
FROM LOAN
WHERE BRANCH_CODE IN ('B001','B002','B004');

SELECT ACC_TYPE, COUNT(*), SUM(BALANCE)
FROM ACCOUNT
GROUP BY ACC_TYPE;

SELECT TRANS_TYPE, SUM(TRANS_AMOUNT)
FROM TRANSACTION_DETAILS
WHERE ACC_NO <> 'A1005'
GROUP BY TRANS_TYPE;

SELECT SUM(BALANCE)
FROM ACCOUNT
WHERE ACC_TYPE='Current';

SELECT ACC_TYPE, COUNT(*)
FROM ACCOUNT
GROUP BY ACC_TYPE
ORDER BY COUNT(*) ASC;

SELECT TRANS_TYPE, COUNT(*)
FROM TRANSACTION_DETAILS
GROUP BY TRANS_TYPE
ORDER BY COUNT(*) DESC;

SELECT ACC_TYPE, AVG(BALANCE)
FROM ACCOUNT
GROUP BY ACC_TYPE
HAVING AVG(BALANCE) > 25000;

SELECT ACC_TYPE, COUNT(*)
FROM ACCOUNT
GROUP BY ACC_TYPE
HAVING COUNT(*) > 2;

SELECT ACC_TYPE, MAX(BALANCE)
FROM ACCOUNT
GROUP BY ACC_TYPE
HAVING MAX(BALANCE) > 40000;

SELECT MAX(BALANCE)
FROM ACCOUNT
WHERE ACC_TYPE='Savings';

SELECT TRANS_TYPE
FROM TRANSACTION_DETAILS
GROUP BY TRANS_TYPE
ORDER BY SUM(TRANS_AMOUNT) DESC
LIMIT 1;

SELECT ACC_TYPE
FROM ACCOUNT
GROUP BY ACC_TYPE
HAVING SUM(BALANCE) >
(
    SELECT AVG(BALANCE)
    FROM ACCOUNT
);

SELECT SUBSTRING('Koushik',2,5);

SELECT LENGTH('Siksha O Anusandhan University');

SELECT UPPER(CUST_NAME)
FROM CUSTOMER;

SELECT LEFT(ACC_TYPE,2)
FROM ACCOUNT;

SELECT MONTH(TRANS_DATE), YEAR(TRANS_DATE)
FROM TRANSACTION_DETAILS;

SELECT DATE_FORMAT(TRANS_DATE,'%d/%m/%Y')
FROM TRANSACTION_DETAILS;

SELECT DATEDIFF(CURDATE(), TRANS_DATE)
FROM TRANSACTION_DETAILS;

SELECT DATE_ADD(CURDATE(), INTERVAL 15 DAY);

SELECT TRUNCATE(94204.27348,2);

