SELECT NAME
FROM INSTRUCTOR
WHERE DEPT_NAME = (
    SELECT DEPT_NAME
    FROM COURSE
    WHERE COURSE_ID = 'CS-101'
);

SELECT DEPT_NAME
FROM DEPARTMENT
WHERE BUDGET > (
    SELECT BUDGET
    FROM DEPARTMENT
    WHERE DEPT_NAME = 'Biology'
);

SELECT DISTINCT S.NAME
FROM STUDENT S
JOIN TAKES T ON S.ID = T.S_ID
JOIN SECTION SEC ON T.COURSE_ID = SEC.COURSE_ID
WHERE SEC.ROOM_NO = (
    SELECT ROOM_NO
    FROM SECTION
    WHERE COURSE_ID = 'CS-101'
    LIMIT 1
);

SELECT S.ID, S.NAME
FROM STUDENT S
WHERE NOT EXISTS (
    (SELECT COURSE_ID
     FROM COURSE
     WHERE DEPT_NAME = 'Comp. Sci.')
    EXCEPT
    (SELECT COURSE_ID
     FROM TAKES
     WHERE S_ID = S.ID)
);

SELECT DISTINCT COURSE_ID
FROM SECTION
WHERE BUILDING = (
    SELECT BUILDING
    FROM CLASSROOM
    WHERE ROOM_NO = 514
);

SELECT NAME
FROM INSTRUCTOR I
WHERE NOT EXISTS (
    SELECT *
    FROM TEACHES T
    WHERE T.ID = I.ID AND SEMESTER = 'Spring'
);

SELECT NAME
FROM STUDENT
WHERE DEPT_NAME = (
    SELECT DEPT_NAME
    FROM DEPARTMENT
    WHERE BUDGET = (
        SELECT MAX(BUDGET) FROM DEPARTMENT
    )
);

SELECT I.ID, I.NAME
FROM INSTRUCTOR I
JOIN ADVISOR A ON I.ID = A.I_ID
WHERE A.S_ID = '44553';

SELECT T.COURSE_ID, T.YEAR
FROM TAKES T
JOIN STUDENT S ON T.S_ID = S.ID
WHERE S.NAME = 'Srinivasan'
AND T.SEMESTER = 'Fall';

CREATE TABLE SEMESTER_TYPE AS
SELECT SEMESTER, YEAR
FROM SECTION
WHERE 1=0;

INSERT INTO SEMESTER_TYPE (SEMESTER, YEAR)
SELECT SEMESTER, YEAR
FROM SECTION
WHERE ROOM_NO < 500;

UPDATE SEMESTER_TYPE
SET SEMESTER = 'Summer';

DELETE FROM SEMESTER_TYPE;

SELECT ID, NAME
FROM STUDENT
WHERE TOT_CRED > SOME (
    SELECT TOT_CRED
    FROM STUDENT
    WHERE DEPT_NAME = 'Comp. Sci.'
);

SELECT NAME
FROM STUDENT
WHERE TOT_CRED > ALL (
    SELECT TOT_CRED
    FROM STUDENT
    WHERE DEPT_NAME = 'Comp. Sci.'
);

SELECT *
FROM INSTRUCTOR I
WHERE EXISTS (
    SELECT *
    FROM TEACHES T
    WHERE T.ID = I.ID
);

SELECT *
FROM INSTRUCTOR I
WHERE NOT EXISTS (
    SELECT *
    FROM TEACHES T
    WHERE T.ID = I.ID
);

UPDATE INSTRUCTOR
SET SALARY =
    CASE
        WHEN SALARY > 80000 THEN SALARY * 1.08
        ELSE SALARY * 1.06
    END;





SELECT DISTINCT I.NAME
FROM INSTRUCTOR I
JOIN TEACHES T ON I.ID = T.ID
WHERE T.SEMESTER = 'Summer';

SELECT DISTINCT S.NAME
FROM STUDENT S
JOIN TAKES T ON S.ID = T.S_ID
JOIN COURSE C ON T.COURSE_ID = C.COURSE_ID
WHERE C.DEPT_NAME = 'Physics';

SELECT DISTINCT SEC.BUILDING
FROM SECTION SEC
JOIN COURSE C ON SEC.COURSE_ID = C.COURSE_ID
WHERE C.DEPT_NAME = 'Biology';

SELECT DISTINCT S.NAME, S.DEPT_NAME
FROM STUDENT S
JOIN TAKES T ON S.ID = T.S_ID
JOIN TEACHES TE ON T.COURSE_ID = TE.COURSE_ID
JOIN INSTRUCTOR I ON TE.ID = I.ID
WHERE I.SALARY > 80000;

SELECT DISTINCT CL.BUILDING, CL.CAPACITY
FROM CLASSROOM CL
JOIN SECTION SEC ON CL.ROOM_NO = SEC.ROOM_NO AND CL.BUILDING = SEC.BUILDING
JOIN COURSE C ON SEC.COURSE_ID = C.COURSE_ID
WHERE C.DEPT_NAME = 'Comp. Sci.';

SELECT DISTINCT S.NAME
FROM STUDENT S
JOIN TAKES T ON S.ID = T.S_ID
JOIN SECTION SEC ON T.COURSE_ID = SEC.COURSE_ID
WHERE SEC.BUILDING <> 'Watson';

SELECT DISTINCT I.NAME
FROM INSTRUCTOR I
JOIN TEACHES T ON I.ID = T.ID
JOIN SECTION SEC ON T.COURSE_ID = SEC.COURSE_ID
JOIN CLASSROOM C ON SEC.ROOM_NO = C.ROOM_NO
WHERE C.CAPACITY = 500;

SELECT T.SEMESTER, T.GRADE
FROM TAKES T
JOIN TEACHES TE ON T.COURSE_ID = TE.COURSE_ID
JOIN INSTRUCTOR I ON TE.ID = I.ID
WHERE I.NAME = 'Kim';'

SELECT S.NAME, S.TOT_CRED
FROM STUDENT S
JOIN TAKES T ON S.ID = T.S_ID
WHERE T.SEMESTER = 'Fall';

WITH AVG_BUDGET AS (
    SELECT AVG(BUDGET) AS AVG_VAL
    FROM DEPARTMENT
)
SELECT DEPT_NAME
FROM DEPARTMENT, AVG_BUDGET
WHERE BUDGET > AVG_VAL;

