DESC BRANCH;
DESC CUSTOMER;
DESC ACCOUNT;
DESC LOAN;
DESC TRANSACTION_DETAILS;

SELECT * FROM BRANCH;
SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM LOAN;
SELECT * FROM TRANSACTION_DETAILS;

SELECT CUST_NO, BRANCH_CODE
FROM ACCOUNT;

SELECT CUST_NO, BALANCE
FROM ACCOUNT
WHERE ACC_TYPE = 'Savings';

SELECT ACC_NO, TRANS_ID
FROM TRANSACTION_DETAILS
WHERE TRANS_TYPE = 'Deposit'
AND TRANS_AMOUNT > 5000;

SELECT *
FROM LOAN
WHERE AMOUNT < 200000;

SELECT CUST_NO
FROM ACCOUNT
WHERE ACC_TYPE != 'Savings';

SELECT DISTINCT CITY
FROM BRANCH;

SELECT ACC_NO
FROM TRANSACTION_DETAILS
WHERE TRANS_DATE BETWEEN '2025-01-01' AND '2025-01-31';

SELECT ACC_NO
FROM ACCOUNT
WHERE BALANCE <> 32000;

SELECT *
FROM ACCOUNT
ORDER BY BALANCE DESC;

ALTER TABLE CUSTOMER
ADD EMAIL VARCHAR(40);

UPDATE CUSTOMER
SET EMAIL='ankit@gmail.com'
WHERE CUST_NO='C001';
UPDATE CUSTOMER
SET EMAIL='anjali@gmail.com'
WHERE CUST_NO='C002';
UPDATE CUSTOMER
SET EMAIL='suresh@gmail.com'
WHERE CUST_NO='C003';
UPDATE CUSTOMER
SET EMAIL='neha@gmail.com'
WHERE CUST_NO='C004';
UPDATE CUSTOMER
SET EMAIL='amit@gmail.com'
WHERE CUST_NO='C005';

ALTER TABLE BRANCH
RENAME COLUMN CITY TO LOCATION;

ALTER TABLE TRANSACTION_DETAILS
RENAME TO BANK_TRANSACTION;

ALTER TABLE ACCOUNT
RENAME COLUMN ACC_NO TO ACCOUNT_NO;

ALTER TABLE CUSTOMER
MODIFY CUST_NAME VARCHAR(50);

ALTER TABLE ACCOUNT
RENAME TO CUSTOMER_ACCOUNT;

ALTER TABLE BRANCH
MODIFY BRANCH_NAME VARCHAR(40);

DELETE FROM BANK_TRANSACTION;